### PR TITLE
Pass entire message to perform_async

### LINKED ISSUE #11: Pass hash message instead of hash values as arguments to perform_async
https://github.com/giftcardzen/la_gear/blob/master/lib/la_gear/worker.rb#L61

### PR DESCRIPTION
**Pull request by crazydog115**
Closes #11 
This passes the entire hash to `perform_async`. 

The workers can then change their signatures from

```ruby
def perform(foo, bar, baz, qux='buzz')
```
to
```ruby
def perform(foo:, bar:, baz:, qux: 'buzz')
```

### CODE REVIEW

**Comment by gabrieljoelc** [comment]
Hmm, we're going to have to fix all of our workers before we can implement this aren't we?

**Comment by crazydog115** [comment]
Yes.

**Comment by crazydog115** [comment]
Now that this gem is legitimate, this can be merged and we can bump up to v2.0.0 (since this breaks everything), and update the other apps individually. Yay!

**Comment by gabrieljoelc** [comment]
We should git-flowify la_gear, merge this into develop, and then add a few more things in before we merge it into master. Good opportunity for a milestone?

**Comment by gabrieljoelc** [comment]
Going to branch from `develop`.

**Pull request closed without merging**
